#!/bin/bash

git clone https://github.com/LouisRoss/spiking-model-core.git
cp spiking-model-core/include/ConfigurationRepository.h include/
cp spiking-model-core/include/IModelInitializer.h include/sdk/
cp spiking-model-core/include/ISensorInput.h include/sdk/
cp spiking-model-core/include/KeyListener.h include/sdk/
cp spiking-model-core/include/ModelInitializerProxy.h include/sdk/
cp spiking-model-core/include/ModelInitializer.h include/sdk/
cp spiking-model-core/include/ModelUi.h include/sdk/
cp spiking-model-core/include/Log.h include/
cp spiking-model-core/include/Recorder.h include/
cp spiking-model-core/include/ModelLifeInitializer.h samples/life/include/
cp spiking-model-core/include/ParticleModelInitializer.h samples/particle/include/
rm -rf spiking-model-core/*
rm -rf spiking-model-core/\.*
rmdir spiking-model-core
