#!/bin/bash

git clone https://github.com/LouisRoss/spiking-model-core.git
cp spiking-model-core/include/ConfigurationRepository.h include/
cp spiking-model-core/include/SensorInputProxy.h include/sdk/
cp spiking-model-core/include/KeyListener.h include/sdk/
cp spiking-model-core/include/ModelInitializerProxy.h include/sdk/
cp spiking-model-core/include/ModelUi.h include/sdk/
cp spiking-model-core/include/Log.h include/
cp spiking-model-core/include/Recorder.h include/
cp -R spiking-model-core/include/Initializers include/
cp -R spiking-model-core/include/SensorInputs include/
rm -rf spiking-model-core/*
rm -rf spiking-model-core/\.*
rmdir spiking-model-core
